# Generated by Django 5.1.1 on 2024-09-17 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Auther",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("biography", models.TextField(blank=True, null=True)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("nationality", models.CharField(blank=True, max_length=50, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("awards", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Auther",
                "verbose_name_plural": "Authers",
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(max_length=500)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("NON_FIC", "Non-Fiction"),
                            ("HOR", "Horror"),
                            ("SF", "Science Fiction"),
                            ("FAN", "Fantasy"),
                            ("BIO", "Biography"),
                            ("HIS", "History"),
                            ("PHI", "Philosophy"),
                            ("TRA", "Travel"),
                            ("SELF_HELP", "Self-Help"),
                            ("EDU", "Educational"),
                            ("FIC", "Fiction"),
                        ],
                        default="FIC",
                        max_length=10,
                    ),
                ),
                ("language", models.CharField(blank=True, max_length=50, null=True)),
                ("pages", models.PositiveIntegerField(blank=True, null=True)),
                ("published_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "auther",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_auther",
                        to="book_nest.auther",
                    ),
                ),
            ],
            options={
                "verbose_name": "Book",
                "verbose_name_plural": "Books",
            },
        ),
    ]
